# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/gruvbox_material.toml"]

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 7
y = 0

[shell]
program = "/opt/homebrew/bin/bash"
