#!/bin/bash

timer 10m && terminal-notifier -message 'Pomodoro' \
	-title 'Rest timer has ended - Lets get to work!' \
	-appIcon '~/Downloads/dog.png' \
	-sound Crystal

# pomo stop
#
# if [[ $(dndstatus) = "Do Not Disturb is turned On." ]]; then
# 	dnd
# fi
